### PR TITLE
Upgrade to Ghost 3

### PR DESCRIPTION
**Pull request by genuinezack**
1. Upgrade the package.json dependencies to Ghost 3.0.0 and `ghost-storage-cloudinary` 2.0.1
2. Update the package.json version to 3.0.0 to keep matching the Ghost version
3. Update the README documentation to reflect the use of `npm` instead of `yarn` and the new 3.x Ghost version.

### CODE REVIEW

**Comment by SNathJr** [comment]
Also, if possible could you create another branch for Ghost-2.x so that those willing to use 2.x can. Keep 3.x in the master branch though. After that, please resubmit the PR.

Thank you.

**Comment by genuinezack** [comment]
I can't create a branch on your repo via PR (as far as I can tell, PRs can only add code to an existing branch if you don't have write access to the repo). Happy to help maintain the repo if you want to give me write access, otherwise you'll have to make the `ghost-2.x` branch yourself before merging this PR in, @SNathJr.

**Comment by SNathJr** [comment]
You could resubmit the PR, but in any case I shall do it myself. Also, I will consider giving you write access.

Cheers!

**Comment by genuinezack** [comment]
Thanks for the merge @SNathJr!

And yeah, I tried forking `master` (pre upgrade) into [a branch on my fork](https://github.com/genuinezack/ghost-on-heroku/tree/Ghost-2.X), but when I try to open a PR from that branch to a branch with the same name on your repository, the Github UI says "There isn’t anything to compare" and refuses to let me open the PR. IDK what's up with that.

**Comment by SNathJr** [comment]
Okay, understood. It must be the case that, PRs can only be made on pre-existing branches.

**Pull request merged**
